site_name: MedMemory AI Technical Docs
site_url: https://medmemory-ai.github.io/docs/
repo_url: https://github.com/MedMemory-AI
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: teal
    - scheme: slate
      primary: teal
      accent: teal

plugins:
  - search

nav:
  - Welcome: index.md

  - Architecture:
      - Server Architecture: Architecture/RAG-Server.md
      - Database Design: Architecture/Database-design.md
      - System Workflows: Architecture/Workflows.md
      - API Reference: Architecture/API-Ref.md

  - Design Decisions:
      - Storage Engine Choices: Design-Decisions/storage.md

  - Tech Stack Overview: Tech-Stack.md

  - Folder Structure: Folder-Structure.md

  - Guides:
    - User Guide: Guides/How-to-Use.md
    - Local Setup: Guides/Local-Setup.md
    - Contributing: Guides/Contributing-Guide.md
    - Deployment:
      - AWS EKS: Guides/Deployment/AWS-EKS.md
      - OCI: Guides/Deployment/OCI.md

  - Roadmap: Roadmap.md

  - FAQ: FAQ.md
